todoList.Web/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace todoList.Web.Controllers
{
    [Authorize(Roles="admin")]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

todoList.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.Logging;
using todoList.Business.Interfaces;
using todoList.DTOS.Requests;
using todoList.Entities.Base;
using todoList.Web.Models;

namespace todoList.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly ITaskService taskService;
        private readonly IListService listService;

        private readonly ILogger<UserController> logger;
        public UserController(IUserService userService, ILogger<UserController> logger
        ,ITaskService taskService, IListService listService)
        {
            this.userService = userService;
            this.taskService = taskService;
            this.listService = listService;
            this.logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            
            var userName = User.Identity.Name;
            if (userName == null) return RedirectToAction(nameof(Login));
            
            var userId = await userService.GetUserIdByUsername(userName);
            var lists = await listService.GetAllListOfUserAsync(userId);
            var tasks = await taskService.GetTasksByUserId(userId);
            var user = await userService.GetUserById(userId);

            ViewBag.Lists = lists.ToList();
            ViewBag.Tasks = tasks.ToList();

            return View(user);
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (User.Identity.Name == null) return RedirectToAction(nameof(Index));
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserLoginModel model)
        {
            if (!ModelState.IsValid) return View();

            var user = await userService.ValidateUserAsync(model.UserName, model.Password);

            if (user != null)
            {
                ICollection<Claim> claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                    new Claim(ClaimTypes.Name, user.UserName),
                    new Claim(ClaimTypes.Email, user.Email),
                    new Claim(ClaimTypes.Role, user.Role)
                };
                ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(principal);

                logger.LogInformation($"{DateTime.UtcNow.ToLongTimeString()} | '{user.UserName}({user.Id})' logged in.");

                return RedirectToAction(nameof(Index));
            }

            if (await userService.IsUserNameExistAsync(model.UserName))
            {
                logger.LogWarning($"{DateTime.UtcNow.ToLongTimeString()} | '{model.UserName}' tried to login with wrong password.");
                ModelState.AddModelError(nameof(Login), "Your password is wrong.");
            }
            else
            {
                ModelState.AddModelError(nameof(Login), "Username or password is wrong.");
            }
            
            return View();
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp([Bind("Email", "UserName", "Password")]CreateUserRequest user)
        {
            if (!ModelState.IsValid)
            {
                foreach (var modelState in ViewData.ModelState.Values) {
                    foreach (ModelError error in modelState.Errors) {
                        logger.LogDebug(error.ToString());
                    }
                }

                return View();
            }
            if (await userService.IsEmailExistAsync(user.Email))
            {
                ModelState.AddModelError(nameof(SignUp),"This email already used.");
                return View();
            }

            if (await userService.IsUserNameExistAsync(user.UserName))
            {
                ModelState.AddModelError(nameof(SignUp), "This user name already used.");
                return View();
            }


            int userId = await userService.AddUser(user);
            logger.LogInformation($"{DateTime.UtcNow.ToLongTimeString()} | New user registered as '{user.UserName}({userId})' with '{user.Email}' email.");
            return RedirectToAction(nameof(Index), "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Index), "Home");
        }
    }
}

todoList.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@{ bool isAuthenticated = User.Identity.IsAuthenticated; }

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - todoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <style>
        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="username"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
</head>
<body>
<!-- Symbols -->
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="home" viewBox="0 0 16 16">
        <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"></path>
    </symbol>
    <symbol id="speedometer2" viewBox="0 0 16 16">
        <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"></path>
        <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"></path>
    </symbol>
    <symbol id="table" viewBox="0 0 16 16">
        <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"></path>
    </symbol>
    <symbol id="people-circle" viewBox="0 0 16 16">
        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
    </symbol>
    <symbol id="grid" viewBox="0 0 16 16">
        <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"></path>
    </symbol>
</svg>
<!-- Header-->
<header>
    <!-- navbar -->
    <nav>
        <div class="px-3 py-2 bg-dark text-white">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
                    </a>

                    <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
                        <li>
                            <a asp-action="Index" asp-controller="Home" class="nav-link text-secondary">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"></use></svg>
                                Home
                            </a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="List" class="nav-link text-white">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#speedometer2"></use></svg>
                                Lists
                            </a>
                        </li>
@*                        <li>
                            <a href="#" class="nav-link text-white">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#table"></use></svg>
                                Orders
                            </a>
                        </li>
                        <li>
                            <a href="#" class="nav-link text-white">
                                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"></use></svg>
                                Products
                            </a>
                        </li>*@
                        @if (isAuthenticated)
                        {
                            <li>
                                <a asp-action="Index" asp-controller="User" class="nav-link text-white" style="color:darkorange">
                                    <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#people-circle"></use></svg>
                                    Profile
                                </a>
                            </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                            <li>
                                <a asp-action="Index" asp-controller="Admin" class="nav-link text-white">
                                    <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#people-circle"></use></svg>
                                    Admin
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- user bar -->
    <div class="px-3 py-2 border-bottom mb-3">
        <div class="container d-flex flex-wrap justify-content-center">
            <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto" role="search">
                @*<input type="search" class="form-control" placeholder="Search..." aria-label="Search">*@
            </form>
            <div class="text-end">
                @if (isAuthenticated)
                {
                    <span class="navbar-text">Hello, @User.Identity.Name</span>
                    <a class="btn btn-primary" asp-action="Logout" asp-controller="User">Logout</a>
                }
                else
                {
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" href="#loginModal" role="button">Login</button>
                    <a class="btn btn-light text-dark me-2" asp-action="SignUp" asp-controller="User">Sign up</a>
                }
            </div>
        </div>
    </div>
</header>
<!-- Login modal -->
@*@if (!isAuthenticated)
{
<div class="modal fade" id="loginModal" aria-hidden="true" aria-labelledby="login" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModal">Login</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form class="form-signin" asp-action="Login" asp-controller="User">
                <div class="modal-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-floating">
                        <input asp-for="UserName" type="username" class="form-control" id="floatingInput" placeholder="Username"/>
                        <label for="floatingInput" asp-for="UserName" class="form-control" style="background-color: transparent; text-align: left; line-height: 0.25">Username</label>
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="form-floating">
                        <input asp-for="Password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                        <label for="floatingPassword" asp-for="Password" class="form-control" style="background-color: transparent; text-align: left; line-height: 0.25">Password</label>
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="Login">
                    <a class="btn btn-light text-dark me-2" asp-action="SignUp" asp-controller="User">Sign up</a>
                </div>
            </form>
            <div asp-validation-summary="All"></div>
        </div>
    </div>
</div>
*@
@*<div class="modal fade" id="signupModal" aria-hidden="true" aria-labelledby="signup" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="signupModal">Sign up</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form class="form-signin">
                <div class="modal-body">
                    Hide this modal and show the first with the button below.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light text-dark me-2" asp-action="Signup", asp-controller="User">Sign-up</button>
                    <button type="button" class="btn btn-primary" data-bs-target="#loginModal" data-bs-toggle="modal">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>*@
}

<!-- Main -->
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>


<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - todoList.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>


@{
    // TODO Nav menu will be changed
    // TODO After implementing signing up, form will be added to nav menu.
}