todoList.Web/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using todoList.Business.Interfaces;
using todoList.DTOS.Requests;
using todoList.Entities.Base;
using todoList.Web.Extensions;

namespace todoList.Web.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private readonly IUserService userService;
        private readonly ITaskService taskService;
        private readonly IListService listService;
        private readonly ILogger<TasksController> logger;

        public TasksController(IUserService userService, ITaskService taskService,
            IListService listService, ILogger<TasksController> logger)
        {
            this.userService = userService;
            this.listService = listService;
            this.taskService = taskService;
            this.logger = logger;
        }

        public IActionResult Index(int? listId)
        {
            return listId == null ? NotFound() : RedirectToAction(nameof(Index), "List", new { listId = listId });
        }

        [HttpGet]
        public async Task<IActionResult> Create(int listId)
        {
            ViewBag.Priorities = await GetPriorities();
            ViewBag.Statuses = await GetStatuses();
            ViewBag.User = await GetUser();
            ViewBag.ListId = listId;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTaskRequest task)
        {
            if (ModelState.IsValid)
            {
                User user = await GetUser();
                task.CreatedById = user.Id;

                int addedTaskId = await taskService.AddTask(task);

                logger.LogInformation(
                    $"{DateTime.UtcNow.ToLongTimeString()} | " +
                    $"New task '{task.Name} ({addedTaskId})' added to {task.TListId} list by {user.UserName}"); 

                return RedirectToAction(nameof(Index), "List", new { listId = task.TListId });
            }
            

            foreach (var error in ModelState.Values.SelectMany(stateValue => stateValue.Errors))
            {
                logger.LogWarning(error.ErrorMessage);
            }

            ModelState.AddModelError(nameof(Create), "This model is wrong.");
            return View();
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(int taskId)
        {
            bool isExist = await taskService.IsExist(taskId);
            if (!isExist) return NotFound();

            var task = await taskService.GetTaskById(taskId);
            var userId = await User.GetIdAsync();

            if (userId != task.CreatedById) return RedirectToAction("AccessDenied", "Home");

            ViewBag.Priorities = await GetPriorities();
            ViewBag.Statuses = await GetStatuses();

            return View(task);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UpdateTaskRequest task)
        {
            if (ModelState.IsValid)
            {
                int affectedRowsCount = await taskService.UpdateTask(task);

                if (affectedRowsCount > 0) return RedirectToAction(nameof(Index), "User");

                return BadRequest();
            }

            logger.LogInformation(
                $"{DateTime.UtcNow.ToLongTimeString()} | " +
                $"New task '{task.Name} ({task.Id})' updated by {User.Identity.Name}");

            ViewBag.Priorities = await GetPriorities();
            ViewBag.Statuses = await GetStatuses();
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int taskId)
        {
            if (await taskService.IsExist(taskId) )
            {
                var task = await taskService.GetTaskById(taskId);

                var userId = await User.GetIdAsync();
                if (userId != task.CreatedById) return RedirectToAction("AccessDenied", "Home");

                return View(task);
            }

            return NotFound();
        }

        [HttpPost]
        [ActionName(nameof(Delete))]
        public async Task<IActionResult> DeleteTask(int taskId)
        {
            await taskService.DeleteTask(taskId);
            return RedirectToAction(nameof(Index), "User");
        }


        private async Task<List<SelectListItem>> GetPriorities()
        {
            List<SelectListItem> prioritiesList = new List<SelectListItem>();

            var priorities = (await taskService.GetAllPrioritiesAsync()).ToList();

            priorities.ForEach(p => prioritiesList.Add(
                new SelectListItem{ Text=p.Name, Value=p.Id.ToString() } 
            ));

            return prioritiesList;
        }
        private async Task<List<SelectListItem>> GetStatuses()
        {
            List<SelectListItem> statusesList = new List<SelectListItem>();

            var statuses = (await taskService.GetAllStatusesAsync()).ToList();

            statuses.ForEach(s => statusesList.Add(
                new SelectListItem{ Text=s.Name, Value=s.Id.ToString() } 
            ));

            return statusesList;
        }
        private async Task<User> GetUser() => await User.GetUserAsync(userService);
    }
}

todoList.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.Logging;
using todoList.Business.Interfaces;
using todoList.DTOS.Requests;
using todoList.Entities.Base;
using todoList.Web.Models;

namespace todoList.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly ITaskService taskService;
        private readonly IListService listService;

        private readonly ILogger<UserController> logger;
        public UserController(IUserService userService, ILogger<UserController> logger
        ,ITaskService taskService, IListService listService)
        {
            this.userService = userService;
            this.taskService = taskService;
            this.listService = listService;
            this.logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            
            var userName = User.Identity.Name;
            if (userName == null) return RedirectToAction(nameof(Login));
            
            var userId = await userService.GetUserIdByUsername(userName);
            var lists = await listService.GetAllListOfUserAsync(userId);
            var tasks = await taskService.GetTasksByUserId(userId);
            var user = await userService.GetUserById(userId);

            ViewBag.Lists = lists.ToList();
            ViewBag.Tasks = tasks.ToList();

            return View(user);
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (User.Identity.Name == null) return RedirectToAction(nameof(Index));
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserLoginModel model)
        {
            if (!ModelState.IsValid) return View();

            var user = await userService.ValidateUserAsync(model.UserName, model.Password);

            if (user != null)
            {
                ICollection<Claim> claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                    new Claim(ClaimTypes.Name, user.UserName),
                    new Claim(ClaimTypes.Email, user.Email),
                    new Claim(ClaimTypes.Role, user.Role)
                };
                ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                ClaimsPrincipal principal = new ClaimsPrincipal(identity);

                await HttpContext.SignInAsync(principal);

                logger.LogInformation($"{DateTime.UtcNow.ToLongTimeString()} | '{user.UserName}({user.Id})' logged in.");

                return RedirectToAction(nameof(Index));
            }

            if (await userService.IsUserNameExistAsync(model.UserName))
            {
                logger.LogWarning($"{DateTime.UtcNow.ToLongTimeString()} | '{model.UserName}' tried to login with wrong password.");
                ModelState.AddModelError(nameof(Login), "Your password is wrong.");
            }
            else
            {
                ModelState.AddModelError(nameof(Login), "Username or password is wrong.");
            }
            
            return View();
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp([Bind("Email", "UserName", "Password")]CreateUserRequest user)
        {
            if (!ModelState.IsValid)
            {
                foreach (var modelState in ViewData.ModelState.Values) {
                    foreach (ModelError error in modelState.Errors) {
                        logger.LogDebug(error.ToString());
                    }
                }

                return View();
            }
            if (await userService.IsEmailExistAsync(user.Email))
            {
                ModelState.AddModelError(nameof(SignUp),"This email already used.");
                return View();
            }

            if (await userService.IsUserNameExistAsync(user.UserName))
            {
                ModelState.AddModelError(nameof(SignUp), "This user name already used.");
                return View();
            }


            int userId = await userService.AddUser(user);
            logger.LogInformation($"{DateTime.UtcNow.ToLongTimeString()} | New user registered as '{user.UserName}({userId})' with '{user.Email}' email.");
            return RedirectToAction(nameof(Index), "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Index), "Home");
        }
    }
}

todoList.Web/Views/Shared/Components/_DeleteViewTaskResponseButton.cshtml
@model ViewTaskResponse

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#deleteModal">
    Delete
</button>
<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h5 class="card-title">@Model.Name</h5>
                <h6 class="card-subtitle mb-2 text-muted">@Model.PriorityName | @Model.StatusName</h6>
                <p class="card-text">@Model.Description</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form asp-action="Delete" asp-controller="Tasks" asp-route-taskId="@Model.Id">
                    <input asp-for="Id" value="@Model.Id" hidden/>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

todoList.Web/Views/Shared/Components/_LoginForm.cshtml
@model UserLoginModel

<form asp-action="Login" asp-controller="User">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-floating mb-3">
        <input asp-for="UserName" type="username" class="form-control rounded-3" id="floatingInput" placeholder="Username">
        <label asp-for="UserName" for="floatingInput" style="color: black" reqired>Username</label>
    </div>
    <div class="form-floating mb-3">
        <input asp-for="Password" type="password" class="form-control rounded-3" id="floatingPassword" placeholder="Password">
        <label asp-for="Password" for="floatingPassword" style="color: black" required>Password</label>
    </div>
    <span asp-validation-for="UserName" class="text-danger"></span>
    <span asp-validation-for="Password" class="text-danger"></span>
    <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit" value="Login">Login</button>
</form>

todoList.Web/Views/Shared/Components/_SignupForm.cshtml
@model UserSignUpModel

<form asp-action="SignUp" asp-controller="User">
    <div class="form-floating mb-3">
        <input asp-for="UserName" type="username" class="form-control rounded-3" id="floatingInput" placeholder="Username">
        <label asp-for="UserName" for="floatingInput" style="color: black" required>User name</label>
    </div>
    <div class="form-floating mb-3">
        <input asp-for="Email" type="email" class="form-control rounded-3" id="floatingInput" placeholder="name@example.com">
        <label asp-for="Email" for="floatingInput" style="color: black" required>Email address</label>
    </div>
    <div class="form-floating mb-3">
        <input asp-for="Password" type="password" class="form-control rounded-3" id="floatingPassword" placeholder="Password">
        <label asp-for="Password" for="floatingPassword" style="color: black" required>Password</label>
    </div>
    <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit" value="SignUp">Sign up</button>
    <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
</form>

todoList.Web/Views/Shared/Components/_TaskCard.cshtml
@model ViewTaskResponse
<div class="card" style="width: 20rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <h6 class="card-subtitle mb-2 text-muted">Priority : @Model.PriorityName | Status : @Model.StatusName</h6>
        <p class="card-text">@Model.Description</p>
        <p class="card-text">Due date : @Model.DueDate.ToString()</p>

        <a asp-action="Edit" asp-controller="Tasks" asp-route-taskId="@Model.Id" class="card-link btn btn-primary">Edit</a>
        <partial name="Components/_DeleteViewTaskResponseButton" model="@Model"/>
    </div>
</div>